common:
  dataset: "wxb"
  lid_topic: "points_raw"
  imu_topic: "imu_raw"
  time_sync_en: false         # ONLY turn on when external time synchronization is really not possible

preprocess:
  lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
  scan_line: 32
  time_scale: 1e-3             # 兼容不同数据集的时间单位，仅对Velodyne LiDAR(lidar_type=2)生效

mapping:
  extrinsic_T: [ 0, 0, 0 ]
  extrinsic_R: [ 1, 0, 0,
                 0, 1, 0,
                 0, 0, 1 ]


point_filter_num: 10
max_iteration: 3
imu_has_gravity: false
with_ui: false

